plugins:
  - preset-lint-recommended
  - remark-preset-lint-markdown-style-guide
  - remark-validate-links
  # https://github.com/remarkjs/remark-lint/blob/main/doc/rules.md
  - [ 'remark-frontmatter', 'yaml' ]
  - [ 'remark-lint-heading-style', 'atx' ]
  - [ 'remark-lint-maximum-line-length', false ]
  - [ 'remark-lint-no-emphasis-as-heading' ]
  - [ 'remark-lint-emphasis-marker', '_' ]
  - [ 'remark-lint-unordered-list-marker-style', '*' ]
  - [ 'remark-lint-list-item-indent', 2 ]
  - [ 'remark-lint-no-empty-sections' ]
  - [ 'remark-lint-no-tabs' ]
  - [ 'remark-lint-first-heading-level', 2 ]
  - [ 'remark-lint-heading-sentence-case' ]
  - [ 'remark-lint-prohibited-strings', [
      { no: 'Flow node', yes: 'Flow-node' },
      { no: 'flow node', yes: 'flow-node' },
      { yes: 'flow-node' }, # case insensitive
      { no: 'Flow trigger', yes: 'Flow-trigger' },
      { no: 'flow trigger', yes: 'flow-trigger' },
      { yes: 'flow-trigger' },  # case insensitive
      { no: 'Javascript', yes: 'JavaScript' },
      { no: 'Node.JS', yes: 'Node.js' },
      { no: 'NPM', yes: 'npm' },
      { no: 'UNIX', yes: 'unix' },
      { no: "Github", yes: "GitHub" },
      # the plugin doesn't handle regex too well, so wasn't able to use
      # negative lookbehind for use of "builder" without preceeding "API".
      # https://github.com/Trott/remark-lint-prohibited-strings/blob/main/index.js
      { no: 'builder', yes: 'Builder' },
      { no: "can't", yes: 'cannot' },
      { no: "it's", yes: 'it is' },
      { no: "that's", yes: 'that is' },
      { no: "won't", yes: 'will not' },
      { no: "(\\w+)'ve", yes: '$1 have' },
      { no: "(\\w+)n't", yes: '$1 not' },
      { no: "(\\w+)'ll", yes: '$1 will', replaceCaptureGroups: true },
    ]]
