name: CI workflow

# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: MarkdownChecks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run build
        run: |
          npm install
  publish:
    runs-on: ubuntu-latest
    env:
      API_BUILDER_DOCS_PRIVATE_KEY: ${{ secrets.API_BUILDER_DOCS_PRIVATE_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up SSH (upload.zoominsoftware.io)
        run: |
          echo "$API_BUILDER_DOCS_PRIVATE_KEY" > ~/docs.pem
          chmod 600 ~/docs.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host upload.zoominsoftware.io\nHostname upload.zoominsoftware.io\nUser axway\nPort 22\nIdentityFile ~/docs.pem\nPasswordAuthentication no" > ~/.ssh/config
          ssh-keyscan -H upload.zoominsoftware.io > ~/.ssh/known_hosts

    # - name: Configure
    #   run: |
    #     echo "$API_BUILDER_DOCS_PRIVATE_KEY" > ~/docs.pem
    #     chmod 600 ~/docs.pem
    #     mkdir -p ~/.ssh
    #     chmod 700 ~/.ssh
    #     echo -e "Host upload.zoominsoftware.io\nHostname upload.zoominsoftware.io\nUser axway\nPort 22\nIdentityFile ~/docs.pem\nPasswordAuthentication no" > ~/.ssh/config
    #     ssh-keyscan -H upload.zoominsoftware.io > ~/.ssh/known_hosts

    # - name: LFTP Deploy
    #   uses: MajorVengeance/Ftp-Deploy-Action@v0.2.3-alpha
    #   with:
    #     ftp_host: upload.zoominsoftware.io
    #     local_source_dir: ./publish/apibuilderPOC-open-docs-20210729.zip
    #     dist_target_dir: /axway.zoominsoftware.io/confluence/incoming
