name: CI workflow

# Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: MarkdownChecks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v2
    # Use Node.js
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    # Runs markdownlint
    - name: Run markdown linter
      run: |
        npm i -g markdownlint-cli
        markdownlint "content/en/**/*.md"
  publish:
    name: Publish staging
    uses: docker://sebble/deploy
    env:
      API_BUILDER_DOCS_PRIVATE_KEY: ${{ secrets.API_BUILDER_DOCS_PRIVATE_KEY }}
    steps:
    - name: Configure
      run: |
        echo "$API_BUILDER_DOCS_PRIVATE_KEY" > ~/docs.pem
        chmod 600 ~/docs.pem
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo -e "Host upload.zoominsoftware.io\nHostname upload.zoominsoftware.io\nUser axway\nPort 22\nIdentityFile ~/docs.pem\nPasswordAuthentication no" > ~/.ssh/config
        ssh-keyscan -H upload.zoominsoftware.io > ~/.ssh/known_hosts
    - name: Publish FTP
      run: |
        lftp -c 'connect sftp://upload.zoominsoftware.io; put -O /axway.zoominsoftware.io/confluence/incoming/ ./publish/apibuilderPOC-open-docs-20210729.zip; quit'
