name: CI workflow

# Triggers the workflow on push or pull request
# events for the master branch and branch starts with rdpp-
on:
  push:
    branches: [ master, /^rdpp-.*$/ ]
  pull_request:
    branches: [ master, /^rdpp-.*$/ ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: MarkdownChecks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run build
        run: |
          npm install
          npm run build:lint
